import { Link } from "react-router-dom";
import { BETA_CONTACT } from "../../../shared/firebase-config.js";

export default function Terms() {
  const year = new Date().getFullYear();
  return (
    <article className="legal">
      <Link className="back" to="/">← Back to Kanee</Link>
      <h1>Terms of Service</h1>
      <p className="updated">Last updated: {year} · Beta</p>

      <div className="legal-note">
        Kanee is in a private beta. These terms are intentionally simple and may change before
        launch. This is not legal advice — review and adapt before relying on it commercially.
      </div>

      <h2>1. What Kanee is</h2>
      <p>Kanee is a 3D anime AI companion you interact with by voice or text. The service is
      provided "as is" and "as available" during the beta, with no guarantee of uptime,
      availability, or fitness for any purpose.</p>

      <h2>2. Accounts &amp; access</h2>
      <ul>
        <li>You need an account to use the chat, and beta access is granted manually at our discretion.</li>
        <li>You're responsible for keeping your credentials secure and for activity under your account.</li>
        <li>You must be old enough to form a binding agreement in your country (and at least 13).</li>
        <li>We may suspend or remove access at any time during the beta, especially for misuse.</li>
      </ul>

      <h2>3. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use Kanee for anything illegal, harmful, harassing, or abusive.</li>
        <li>Attempt to break, overload, reverse-engineer, or bypass access controls of the service.</li>
        <li>Use the service to generate content that violates others' rights.</li>
      </ul>

      <h2>4. AI-generated content</h2>
      <p>Kanee's replies are generated by AI and may be inaccurate or inappropriate. Don't rely on
      them as professional, medical, legal, or financial advice. You use AI output at your own
      discretion.</p>

      <h2>5. Payment</h2>
      <p>The beta is free. Paid plans are not active yet; if and when they launch, pricing and
      billing terms will be presented before you're charged.</p>

      <h2>6. Intellectual property</h2>
      <p>The Kanee software, character, and branding remain ours. You keep ownership of the text you
      submit, and grant us the limited right to process it to operate the service (including the
      companion's memory features).</p>

      <h2>7. Termination</h2>
      <p>You can stop using Kanee and request deletion of your account at any time. We may end or
      change the beta at any time.</p>

      <h2>8. Liability</h2>
      <p>To the maximum extent permitted by law, we are not liable for any indirect or consequential
      damages arising from your use of the beta service.</p>

      <h2>9. Contact</h2>
      <p>Questions about these terms? Email <a href={`mailto:${BETA_CONTACT}`}>{BETA_CONTACT}</a>.</p>

      <p className="more"><Link className="back" to="/privacy">Privacy Policy →</Link></p>
    </article>
  );
}
